platform :ios, '9.0'
use_frameworks!

target 'RxSwift_Instagram' do
  
  # Pods for RxSwift_Instagram
  # ignore all warnings from all pods
  inhibit_all_warnings!

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'Kingfisher', '4.8'
  pod 'ObjectMapper', '~> 3.3.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod "Pastel"
  pod "RxGesture"
  pod 'YPImagePicker'
  
end
